#!/bin/bash
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

FILES=$(git diff --cached --name-only --diff-filter=ACM "*.cs" "*.csproj" "*.props" "*.sln" "*.config")
if [ -z "$FILES" ]; then
	exit 0
fi

# build
echo -e "${YELLOW}Running pre-commit hook, dotnet build...${NC}"
dotnet build
rc=$?
if [[ $rc != 0 ]] ; then
	echo -e "${RED}Build failed, please fix and commit again. To skip pre-commit hook use 'git commit --no-verify'.${NC}"
	exit $rc
fi

# test
echo -e "${YELLOW}Running pre-commit hook, dotnet test...${NC}"
dotnet test --no-build --filter "Category!=FUNCTIONAL"
rc=$?
if [[ $rc != 0 ]] ; then
	echo -e "${RED}Test(s) failed, please fix and commit again. To skip pre-commit hook use 'git commit --no-verify'.${NC}"
	exit $rc
fi

# format
echo -e "${YELLOW}Running pre-commit hook, dotnet format...${NC}"
dotnet format whitespace --folder --include $FILES
echo "$FILES" | xargs git add
rc=$?

if [[ $rc != 0 ]] ; then
	echo -e "${RED}Failed to format, please fix and commit again. To skip pre-commit hook use 'git commit --no-verify'.${NC}"
	exit $rc
fi

exit 0
